### ISSUE TITLE
External labels are incorrectly processed when used in code in structs

### ISSUE THREAD

**Issue by breakmit-0** [RPGHacker/asar#218]
when writing code in a struct, any label has its first character replaced by '.' and is then assumed to be part of the struct:

```asm
org $008000
struct test $008000
    .label1
    jmp ExternalLabel ;incorrect

    .label2
    jmp .label1  ;works fine

    .label3
    jmp Zlabel1  ;incorrect, should throw an error but refers to test.label1
endstruct

ExternalLabel:

```
 
`test.asm:6: error: (E5060): Label 'test.xternalLabel' wasn't found. [jmp ExternalLabel]`

**Comment by RPGHacker** [comment]
This is a funny one. Didn't know structs did weird stuff with label names.

Wonder what the correct behavior here should be. Just throw errors for most commands/opcodes when used inside structs? Seems like the most reasonable idea.

**Comment by Alcaro** [comment]
[Okay but we fixed that one five months ago,](https://github.com/RPGHacker/asar/commit/42162764bfd13679fe1aa15e79029d0a3efdc0b4) we just didn't make a release since then.

(Or rather, we improved the error into "Invalid label name" x2. I don't know what code in a struct is supposed to mean.)

**Comment by trillllian** [comment]
so, external labels are now allowed in structs properly (in asar 2.0), but opcodes inside structs are not allowed anymore, so the code from the op still doesn't work... the broken error message was fixed in 1.9 too though, so the issue as stated is at least fixed everywhere now. if there's use cases for code in structs then that can be a separate issue
